### ISSUE TITLE
FastNoise Preview default values

### ISSUE THREAD

**Issue by Devilooper** [Auburn/FastNoise_CSharp#10]
I was not able to find stricte Windows Forms source of FastNoisePreview.exe. So my issue is that I have no way of knowing which noise type is used as a default for Noise Lookup, when it comes to Cellular. Also, Gradient Perturb in C# has no simple enum, instead it accepts a bunch of floats. I am specifically looking for the True - Fractal option. Would it be possible to open up to the public those variables?

**Comment by Auburn** [comment]
You can have a look at the code for the preview tool here: https://gist.github.com/Auburns/6c26380869f99e998c5122d044036f2c

All of the options you see in the preview tool are available in the C# version.
