### ISSUE TITLE
Suggestion: audio noise 

### ISSUE THREAD

**Issue by maxima120** [Auburn/FastNoise_CSharp#18]
I am impressed with the performance. One thought crossed my mind - it would be very interesting if you reuse some algorithms and simd experience and make DastAudioNoise variation.

**Comment by Auburn** [comment]
What is DastAudioNoise?

**Comment by maxima120** [comment]
Typo. I was suggesting name for new project Fast not dast :) no special meaning..

**Comment by Auburn** [comment]
I know nothing about audio noise, but isn't it possible to use FastNoise to generate audio waves already?
