### ISSUE TITLE
Seed value doesn't change Simplex/Perlin noise output

### ISSUE THREAD

**Issue by Silentor** [Auburn/FastNoise_CSharp#5]
Hi again!
Next code block outputs equal result for all calls:

```
var fast = new FastNoise(0);
Debug.Log(fast.GetSimplex(1000, 1000));

fast.SetSeed(1000);
Debug.Log(fast.GetSimplex(1000, 1000));

fast.SetSeed(-5000);
Debug.Log(fast.GetSimplex(1000, 1000));
```
Same behavior for GetPerlin() method. I have tried create new instance for every call with no luck. Can I miss something?

**Comment by Auburn** [comment]
Just fixed this, I messed up the seeding with the last optimisation update.

**Comment by Silentor** [comment]
I'v tried another seed experiment, like a:
```
var fast = new FastNoise(0);
for (int i = 0; i < 9; i++)
{
    fast.SetSeed(i);
    Debug.LogFormat("Seed {0}, value {1}", i, fast.GetSimplex(1000, 1000));
}
```
and get a strange aligned results:
Seed 0, value -1.3969838619221E-06
Seed 1, value -6.98491930961051E-07
Seed 2, value 6.98491930961051E-07
Seed 3, value -6.98491930961051E-07
Seed 4, value 9.98400744209508E-25
Seed 5, value 6.98491930961051E-07
Seed 6, value 6.98491930961051E-07
Seed 7, value -6.98491930961051E-07
Seed 8, value 6.98491930961051E-07
Seed 9, value 6.98491930961051E-07

I expect a completely random result values for different seed input values.

**Comment by Auburn** [comment]
You are checking at a simplex grid intersection by using 1000,1000. This will often give similar results back since you are only taking a single gradient from the simplex grid instead of interpolating between them. Try using a more random float as input, or just check yourself with a height map.
