### ISSUE TITLE
Arithmetic overflow

### ISSUE THREAD

**Issue by infiniteperplexity** [Auburn/FastNoise_CSharp#9]
I'm getting the following error:

System.OverflowException: Arithmetic operation resulted in an overflow.

...in this line:

hash = hash * hash * hash * 60493;

I'm a newbie when it comes both to hashing and to C#, but after some poking around online and some experimenting with compilation options...should this code be wrapped in an unchecked {} block so that it doesn't throw an error when checked arithmetic is turned on?

**Comment by Auburn** [comment]
The hashing is designed to overflow, I'd recommend marking all the FastNoise code as unchecked, otherwise it will take a performance hit.
